sudo: required
language: python

python: 3.6

cache: pip

services:
  - postgresql

install:
  - pip install -r requirements.txt

script:
  - pytest -vv --cov . --cov-report xml

after_success:
  - codecov

deploy:
  provider: heroku
  api_key:
    secure: QKNHABTVr87s5+NPvvY1SYZtHhsD8pWI/ejeRKp191Tc5hV9hH4/L11gzsq0meHOI9Z/wJl4P81Gn+HaUBi3EPG/vY6APLjwbqx8GzmNC3Cvh9rfmwJLuwPequM7dw0M2z83htMMvV22PaLGFZjjCQj84GAox2G3tX+b3eVY00NXujNf4uMhpJP6TpZ2NbqHO2ydlhHH/qztOH65fNeM8WCfD9aeFpKaAEsM1t5qp+LC49sOMgPIt2qx+s17yvPWiWPtx9o6gh/4R3WIHoGtHmsmWQhyJbkq8Kkf0FLrgwpJsBw0kI5d8ZqMQ/JdM4r7SDD3wnw5tya3zFuVLFs5Wx7QmWtBAzMlNT2KX+A7dMZzLeb9qWg2NPE8NK0aRz50dPFv4TD/NHE4AEJgGSN3dWAxEba7kSU2ReU+onXk1+fsZmqQrox/GPqVuTkCE1ppRQQ4G1T3SeTjl3//xFc1K3VVd941ZoX3fjbgikserMM6kOiUPggzEI350yXFSwL4I7EHkbWy9rV8lwL9XoxqbkWpT3NEAyPskD3Az0janHKOFzgUGuao7GoKKVQ+XFdzzAp11ZFdnB4Njnvbw/+AlRh2qTAlbo7INJZoz6jVzM9QQoDbOuZRq/zdesYoDUdnAVjg85BMeO6zkU5vHyX9Bs7zRllZ/l305ZTUr5/CLMo=
  app:
    master: travis-tg

notifications:
  webhooks:
    - https://travis-tg.herokuapp.com/u/89599420
    - https://travis-tg.herokuapp.com/u/-1001245180164/force
